// Seed data — mirror of assets/data-*.js, consumed server-side for initial KV fill.
// Keep in sync if you edit assets/data-*.js manually.

export const SEED_TEACHERS = [
  { id: "t_emre",  name: "Emre Günay",         slug: "emre",  meta: "Anaokulu · İlkokul · Ortaokul" },
  { id: "t_halil", name: "Halil İbrahim Eriş", slug: "halil", meta: "Ortaokul · Lise" },
  { id: "t_imge",  name: "İmge Özgencil",      slug: "imge",  meta: "İlkokul" },
  { id: "t_yunus", name: "M. Yunus Toprak",    slug: "yunus", meta: "İlkokul · Ortaokul · Lise" },
];

export const SEED_LESSONS = [
  // --- Emre ---
  { teacherSlug: "emre", gun: 1, bas: "10:55", bit: "11:25", ad: "KAPLAN",   lab: "i", kademe: "anaokulu" },
  { teacherSlug: "emre", gun: 1, bas: "11:30", bit: "12:00", ad: "TİMSAH",   lab: "i", kademe: "anaokulu" },
  { teacherSlug: "emre", gun: 1, bas: "13:20", bit: "13:50", ad: "YUNUS",    lab: "i", kademe: "anaokulu" },
  { teacherSlug: "emre", gun: 1, bas: "14:00", bit: "14:30", ad: "BALİNA",   lab: "i", kademe: "anaokulu" },
  { teacherSlug: "emre", gun: 2, bas: "10:20", bit: "10:50", ad: "PENGUEN",  lab: "i", kademe: "anaokulu" },
  { teacherSlug: "emre", gun: 2, bas: "10:55", bit: "11:25", ad: "PANDA",    lab: "i", kademe: "anaokulu" },
  { teacherSlug: "emre", gun: 2, bas: "11:30", bit: "12:00", ad: "TAVŞAN",   lab: "i", kademe: "anaokulu" },
  { teacherSlug: "emre", gun: 3, bas: "10:05", bit: "10:40", ad: "4/A",      lab: "i", kademe: "ilkokul" },
  { teacherSlug: "emre", gun: 3, bas: "10:50", bit: "11:25", ad: "4/A",      lab: "i", kademe: "ilkokul" },
  { teacherSlug: "emre", gun: 3, bas: "11:35", bit: "12:10", ad: "4/C",      lab: "O", kademe: "ortaokul" },
  { teacherSlug: "emre", gun: 3, bas: "12:55", bit: "13:30", ad: "4/C",      lab: "O", kademe: "ortaokul" },
  { teacherSlug: "emre", gun: 3, bas: "13:45", bit: "14:20", ad: "4/E",      lab: "i", kademe: "ilkokul" },
  { teacherSlug: "emre", gun: 3, bas: "14:35", bit: "15:10", ad: "4/E",      lab: "i", kademe: "ilkokul" },
  { teacherSlug: "emre", gun: 3, bas: "15:25", bit: "16:10", ad: "Toplantı", lab: "",  kademe: "toplanti" },
  { teacherSlug: "emre", gun: 4, bas: "10:50", bit: "11:25", ad: "4/B",      lab: "i", kademe: "ilkokul" },
  { teacherSlug: "emre", gun: 4, bas: "12:55", bit: "13:30", ad: "4/D",      lab: "i", kademe: "ilkokul" },
  { teacherSlug: "emre", gun: 4, bas: "14:35", bit: "15:10", ad: "4/F",      lab: "i", kademe: "ilkokul" },
  { teacherSlug: "emre", gun: 5, bas: "16:15", bit: "16:50", ad: "Amazing",  lab: "i", kademe: "amazing" },

  // --- Halil ---
  { teacherSlug: "halil", gun: 2, bas: "09:50", bit: "10:25", ad: "7B", lab: "L", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 2, bas: "10:40", bit: "11:15", ad: "7A", lab: "L", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 2, bas: "11:25", bit: "12:00", ad: "6A", lab: "L", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 2, bas: "12:10", bit: "12:45", ad: "6A", lab: "L", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 2, bas: "14:00", bit: "14:35", ad: "6B", lab: "O", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 2, bas: "14:45", bit: "15:20", ad: "6B", lab: "O", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 2, bas: "15:40", bit: "16:15", ad: "6D", lab: "O", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 2, bas: "16:25", bit: "17:00", ad: "6D", lab: "O", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 3, bas: "09:00", bit: "09:35", ad: "7E",       lab: "O", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 3, bas: "12:10", bit: "12:45", ad: "6C",       lab: "L", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 3, bas: "14:00", bit: "14:35", ad: "7C",       lab: "L", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 3, bas: "14:45", bit: "15:20", ad: "7D",       lab: "L", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 3, bas: "15:40", bit: "16:15", ad: "Toplantı", lab: "",  kademe: "toplanti" },
  { teacherSlug: "halil", gun: 3, bas: "16:25", bit: "17:00", ad: "6C",       lab: "L", kademe: "ortaokul" },
  { teacherSlug: "halil", gun: 4, bas: "12:20", bit: "12:55", ad: "10/Fen-A", lab: "L", kademe: "lise" },
  { teacherSlug: "halil", gun: 4, bas: "16:10", bit: "16:45", ad: "Amazing",  lab: "i", kademe: "amazing" },
  { teacherSlug: "halil", gun: 5, bas: "14:15", bit: "14:50", ad: "10/AND-A", lab: "L", kademe: "lise" },
  { teacherSlug: "halil", gun: 5, bas: "15:00", bit: "15:35", ad: "10/AND-B", lab: "L", kademe: "lise" },

  // --- İmge ---
  { teacherSlug: "imge", gun: 1, bas: "10:50", bit: "11:25", ad: "3/A", lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 1, bas: "12:55", bit: "13:30", ad: "3/B", lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 1, bas: "14:35", bit: "15:10", ad: "3/C", lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 2, bas: "09:15", bit: "09:50", ad: "1/E", lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 2, bas: "10:50", bit: "11:25", ad: "1/A", lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 2, bas: "12:55", bit: "13:30", ad: "1/B", lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 2, bas: "14:35", bit: "15:10", ad: "1/C", lab: "i", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 3, bas: "10:50", bit: "11:25", ad: "1/D",      lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 3, bas: "13:45", bit: "14:20", ad: "3/E",      lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 3, bas: "14:35", bit: "15:10", ad: "3/D",      lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 3, bas: "15:25", bit: "16:00", ad: "Toplantı", lab: "",  kademe: "toplanti" },
  { teacherSlug: "imge", gun: 4, bas: "09:15", bit: "09:50", ad: "2/E",     lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 4, bas: "16:10", bit: "16:45", ad: "Amazing", lab: "O", kademe: "amazing" },
  { teacherSlug: "imge", gun: 5, bas: "09:15", bit: "09:50", ad: "2/A", lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 5, bas: "10:50", bit: "11:25", ad: "2/B", lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 5, bas: "12:55", bit: "13:30", ad: "2/C", lab: "O", kademe: "ilkokul" },
  { teacherSlug: "imge", gun: 5, bas: "14:35", bit: "15:10", ad: "2/D", lab: "O", kademe: "ilkokul" },

  // --- Yunus ---
  { teacherSlug: "yunus", gun: 1, bas: "13:30", bit: "14:05", ad: "9/Fen-B", lab: "L", kademe: "lise" },
  { teacherSlug: "yunus", gun: 1, bas: "14:15", bit: "14:50", ad: "9/Fen-B", lab: "L", kademe: "lise" },
  { teacherSlug: "yunus", gun: 1, bas: "15:00", bit: "15:35", ad: "9/Fen-A", lab: "L", kademe: "lise" },
  { teacherSlug: "yunus", gun: 1, bas: "15:40", bit: "16:15", ad: "9/Fen-A", lab: "L", kademe: "lise" },
  { teacherSlug: "yunus", gun: 2, bas: "13:30", bit: "14:05", ad: "9/And-B", lab: "L", kademe: "lise" },
  { teacherSlug: "yunus", gun: 2, bas: "14:15", bit: "14:50", ad: "9/And-B", lab: "L", kademe: "lise" },
  { teacherSlug: "yunus", gun: 2, bas: "15:00", bit: "15:35", ad: "9/And-A", lab: "L", kademe: "lise" },
  { teacherSlug: "yunus", gun: 2, bas: "15:40", bit: "16:15", ad: "9/And-A", lab: "L", kademe: "lise" },
  { teacherSlug: "yunus", gun: 3, bas: "09:50", bit: "10:25", ad: "5/C",      lab: "L", kademe: "ortaokul" },
  { teacherSlug: "yunus", gun: 3, bas: "10:40", bit: "11:15", ad: "5/C",      lab: "L", kademe: "ortaokul" },
  { teacherSlug: "yunus", gun: 3, bas: "11:25", bit: "12:00", ad: "5/E",      lab: "L", kademe: "ortaokul" },
  { teacherSlug: "yunus", gun: 3, bas: "15:40", bit: "16:15", ad: "Toplantı", lab: "",  kademe: "toplanti" },
  { teacherSlug: "yunus", gun: 4, bas: "11:35", bit: "12:10", ad: "4/B", lab: "i", kademe: "ilkokul" },
  { teacherSlug: "yunus", gun: 4, bas: "13:45", bit: "14:20", ad: "4/D", lab: "i", kademe: "ilkokul" },
  { teacherSlug: "yunus", gun: 4, bas: "15:25", bit: "16:00", ad: "4/F", lab: "i", kademe: "ilkokul" },
  { teacherSlug: "yunus", gun: 5, bas: "09:50", bit: "10:25", ad: "5/A",        lab: "L", kademe: "ortaokul" },
  { teacherSlug: "yunus", gun: 5, bas: "10:40", bit: "11:15", ad: "5/A",        lab: "L", kademe: "ortaokul" },
  { teacherSlug: "yunus", gun: 5, bas: "11:25", bit: "12:00", ad: "5/B",        lab: "L", kademe: "ortaokul" },
  { teacherSlug: "yunus", gun: 5, bas: "12:10", bit: "12:45", ad: "5/B",        lab: "L", kademe: "ortaokul" },
  { teacherSlug: "yunus", gun: 5, bas: "13:30", bit: "14:05", ad: "Lise Kulüp", lab: "L", kademe: "lise" },
  { teacherSlug: "yunus", gun: 5, bas: "14:00", bit: "14:35", ad: "5/D",        lab: "i", kademe: "ortaokul" },
  { teacherSlug: "yunus", gun: 5, bas: "14:45", bit: "15:20", ad: "5/D",        lab: "i", kademe: "ortaokul" },
  { teacherSlug: "yunus", gun: 5, bas: "15:40", bit: "16:15", ad: "5/E",        lab: "L", kademe: "ortaokul" },
];

export const SCHEMA_VERSION = 1;
